Repository Likelion-backend-IDLE/FindMyDuo, pull requests merged in 2023-09, with the labels that each got.

#67 Feat: 자유게시판 기능 추가
  src/main/java/com/idle/fmd/FmdApplication.java
  src/main/java/com/idle/fmd/domain/board/controller/BoardController.java
  src/main/java/com/idle/fmd/domain/board/dto/BoardAllResponseDto.java
  src/main/java/com/idle/fmd/domain/board/dto/BoardCreateDto.java
  src/main/java/com/idle/fmd/domain/board/dto/BoardResponseDto.java
  src/main/java/com/idle/fmd/domain/board/dto/BoardUpdateDto.java
  src/main/java/com/idle/fmd/domain/board/dto/BookmarkResponseDto.java
  src/main/java/com/idle/fmd/domain/board/dto/LikeBoardResponseDto.java
  src/main/java/com/idle/fmd/domain/board/dto/ReportDto.java
  src/main/java/com/idle/fmd/domain/board/dto/ReportResponseDto.java
  src/main/java/com/idle/fmd/domain/board/entity/BoardEntity.java
  src/main/java/com/idle/fmd/domain/board/entity/BookmarkEntity.java
  src/main/java/com/idle/fmd/domain/board/entity/FileEntity.java
  src/main/java/com/idle/fmd/domain/board/entity/LikeBoardEntity.java
  src/main/java/com/idle/fmd/domain/board/entity/ReportEntity.java
  src/main/java/com/idle/fmd/domain/board/repo/BoardRepository.java
  src/main/java/com/idle/fmd/domain/board/repo/BookmarkRepository.java
  src/main/java/com/idle/fmd/domain/board/repo/FileRepository.java
  src/main/java/com/idle/fmd/domain/board/repo/LikeBoardRepository.java
  src/main/java/com/idle/fmd/domain/board/repo/ReportRepository.java
  src/main/java/com/idle/fmd/domain/board/service/BoardService.java
  src/main/java/com/idle/fmd/domain/board/service/BookmarkService.java
  src/main/java/com/idle/fmd/domain/board/service/LikeBoardService.java
  src/main/java/com/idle/fmd/domain/board/service/ReportService.java
  src/main/java/com/idle/fmd/domain/comment/controller/CommentController.java
  src/main/java/com/idle/fmd/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/idle/fmd/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/idle/fmd/domain/comment/entity/CommentEntity.java
  src/main/java/com/idle/fmd/domain/comment/repo/CommentRepository.java
  src/main/java/com/idle/fmd/domain/comment/service/CommentService.java
  src/main/java/com/idle/fmd/domain/user/controller/UserController.java
  src/main/java/com/idle/fmd/domain/user/entity/UserEntity.java
  src/main/java/com/idle/fmd/domain/user/repo/UserRepository.java
  src/main/java/com/idle/fmd/domain/user/service/UserService.java
  src/main/java/com/idle/fmd/global/auth/jwt/JwtTokenFilter.java
  src/main/java/com/idle/fmd/global/common/entity/BaseTimeEntity.java
  src/main/java/com/idle/fmd/global/config/WebSecurityConfig.java
  src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java
  src/main/java/com/idle/fmd/global/utils/FileHandler.java
  src/main/java/com/idle/fmd/global/utils/RedisUtil.java
Labels: enhancement

#88 Fix: 배포한 SpringBoot 컨테이너가 비정상적으로 종료되는 상황 해결
  src/main/java/com/idle/fmd/global/config/etc/DataSourceConfig.java
Labels: bug

#138 Fix: 롤 계정 연동 시 초기 데이터를 전적 정보까지 저장하도록 수정
  src/main/java/com/idle/fmd/domain/lol/repo/LolMatchRepository.java
  src/main/java/com/idle/fmd/domain/lol/service/LolApiService.java
  src/main/java/com/idle/fmd/domain/user/service/UserService.java
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/mypage.html
Labels: enhancement

#145 Fix: 롤 API 예외 처리 수정 및 마이페이지 프론트 기능 수정
  src/main/java/com/idle/fmd/domain/lol/repo/LolAccountRepository.java
  src/main/java/com/idle/fmd/domain/lol/service/LolApiService.java
  src/main/resources/static/js/mypage.js
Labels: enhancement

#146 Fix: RIOT API 예외 처리 수정 및 마이페이지 프론트 기능 수정
  src/main/java/com/idle/fmd/domain/lol/repo/LolAccountRepository.java
  src/main/java/com/idle/fmd/domain/lol/service/LolApiService.java
  src/main/resources/static/js/mypage.js
Labels: enhancement

#153 Feat: 티어 이름을 가지고 S3에서 티어별 이미지 URL 가져오는 기능 추가
  src/main/java/com/idle/fmd/global/error/exception/BusinessExceptionCode.java
  src/main/java/com/idle/fmd/global/utils/FileHandler.java
Labels: enhancement

#159 Fix: 158 Client 연결 오류 해결
  src/main/java/com/idle/fmd/global/config/etc/WebClientConfig.java
Labels: bug

#161 Fix: ViewController 반환되는 URL 수정 작업
  src/main/java/com/idle/fmd/domain/board/controller/BoardViewController.java
  src/main/java/com/idle/fmd/domain/chating/controller/ChatController.java
Labels: bug

#179 Fix: 좋아요, 즐겨찾기 미로그인 유저 로그인 화면으로 이동
  src/main/resources/static/js/board.js
  src/main/resources/templates/board/board.html
Labels: bug

#187 Refactor: 게시판 이전페이지로 돌아가기 기능, 수정시간 위치 변경
  src/main/resources/static/js/board.js
  src/main/resources/templates/board/board.html
Labels: enhancement

#194 Fix: 신고게시글 이미지 디렉토리 삭제 안되는 문제 해결
  src/main/java/com/idle/fmd/domain/board/service/ReportService.java
Labels: bug

#213 Docs: readme.md 작성
  README.md
Labels: documentation

#214 Docs: readme.md 작성
  README.md
Labels: documentation
